let world = [
{
	"name": "Ahn Adiis",
	"parent": "Cindersands",
	"type": "City",
	"supertype": "Location",
	"summary": "A merchant state of the Cindersands run by an efreet.",
},
{
	"name": "Ahn Ghos",
	"parent": "Cindersands",
	"type": "City",
	"supertype": "Location",
	"summary": "A merchant state of the Cindersands run by a sphinx.",
},
{
	"name": "Ahn Symm",
	"parent": "Cindersands",
	"type": "City",
	"supertype": "Location",
	"summary": "A merchant state of the Cindersands run by a rakshasa.",
},
{
	"name": "Alerodin",
	"parent": "Mihnaria",
	"type": "City",
	"supertype": "Location",
	"summary": "The former capital of Mihnaria and site of the Dragonlight Tower.", // Although the parts of the city nearest the Dragonlight ruins are largely abandoned, the city has been rebuilding away from the ruins.
},
{
	"name": "Altennott",
	"parent": "Mihnaria",
	"type": "City",
	"supertype": "Location",
	"summary": "Mihnarian river port along the border with Dohn Durigg.",
},
{
	"name": "Ano'andil",
	"parent": "Eldenwyld",
	"type": "PoI",
	"subtype": ["River"],
	"supertype": "Location",
	"summary": "The largest river in Eldenwyld, bordering all three major forests at some point along its length.",
},
{
	"name": "Arrodown",
	"parent": "Redwend",
	"type": "City",
	"supertype": "Location",
	"summary": "A river port town in Redwend nearest Nindilwil, the Tower of Ages, and much of Dohn Durigg.", // Legend of founding by refugees whose leader received a prophecy that they should settle where his/her arrow struck the ground. For months, they traveled west, firing an arrow once each day, but every day it struck a tree or a rock and not the ground. Finally, the arrow struck the ground on a hill in Redwend beyond a forest, and the town was founded. 
},
{
	"name": "Atwood Academy",
	"parent": "Ivlin",
	"type": "PoI", //Point of Interest
	"subtype": ["Academy"],
	"supertype": "Location",
	"summary": "A Mihnarian Champion Academy located in Ivlin.  Run by Master Killian Atwood who teaches the skills of the Arcane Trickster.",
},
{
	"name": "Blackburn Mountains",
	"parent": "Dohn Durigg",
	"type": "Region",
	"supertype": "Location",
	"summary": "An ungoverned stretch between Dohn Durigg and Redwend where many go to practice dark arts illegal elsewhere in the world."
},
{
	"name": "Boartrod",
	"parent": "Eldenwyld",
	"type": "City",
	"supertype": "Location",
	"summary": "Eldenwyld town along the southwestern edge of the Lenwood.  Home of the Lost Hall."
},
{
	"name": "Caithe",
	"parent": "Lott",
	"type": "Nation",
	"supertype": "Location",
	"summary": "A seafaring nation in the islands north of Mihnaria and Eldenwyld, along the northern rim of the Sea of Ignavol.  Each island of the nation maintains a temple devoted to a different primal.",
},
{
	"name": "Cindersands",
	"parent": "Lott",
	"type": "Nation",
	"supertype": "Location",
	"summary": "A confederacy of city-states in a scorching desert that lives up to its name.  Loosely governed (mostly taxed) by the Mad King.",
},
{
	"name": "Dohn Durigg",
	"parent": "Lott",
	"type": "Nation",
	"supertype": "Location",
	"summary": "A mountainous land, predominantly populated by dwarves.  Located in the northwest of the continent.",
},
{
	"name": "Dragonlight Tower",
	"parent": "Alerodin",
	"type": "PoI",
	"subtype": ["Tower"], // "Historical" after adding "Dragonlight Ruins"
	"supertype": "Location",
	"summary": "Once one of the Three Towers, but after the Dragonlight Wars it was reduced to a collection of ruins, many of which remain suspended in the air.", // One of the Three Towers, located in Mihnaria.  The Dragonlight Tower was responsible for collecting, sharing, and protecting the world’s knowledge.  It was destroyed by the Dohn Durigg armies during the Second War of Ages.  Many pieces of the tower somehow remain suspended in the air.
	"text": "The Dragonlight Tower once stood in Mihnaria in the city of Alerodin, and within its walls it held the accumulated knowledge of Mihnaria, Redwend, and Eldenwyld. Its halls were woven through extradimensional space to hold its vast libraries. While the Tower of Ages held the source of magical power, all the secrets on how to wield it and all the methods of forging the magical artifacts of Eta Toriel were contained in Dragonlight Tower.",
},
{
	"name": "Drekwater",
	"parent": "Redwend",
	"type": "City",
	"supertype": "Location",
	"summary": "A town in the south of Redwend located on the edge of the Drekwater Marsh.",
	"text": "The Dragonlight Tower once stood in Mihnaria in the city of Alerodin, and within its walls it held the accumulated knowledge of Mihnaria, Redwend, and Eldenwyld. Its halls were woven through extradimensional space to hold its vast libraries. While the Tower of Ages held the source of magical power, all the secrets on how to wield it and all the methods of forging the magical artifacts of Eta Toriel were contained in Dragonlight Tower.",
},
{
	"name": "Drekwater Marsh",
	"parent": "Redwend",
	"type": "Region",
	"supertype": "Location",
	"summary": "A marsh in the south of Redwend.",
},
{
	"name": "Dugg",
	"parent": "Farrokk",
	"type": "City",
	"supertype": "Location",
	"summary": "A hill dwarf town in Farrokk.",
},
{
	"name": "Echoing Hall",
	"parent": "Norgren",
	"type": "PoI",
	"subtype": ["Academy"],
	"supertype": "Location",
	"summary": "A Mihnarian Champion Academy located in Norgren.  Run by Master Everil Everiss, who teaches the Art of the Echoing Blade.",
},
{
	"name": "Eldenwyld",
	"parent": "Lott",
	"type": "Nation",
	"supertype": "Location",
	"summary": "A forested land once occupied by the moon elves.  Once home to the Tower of the Moon.  Located in the eastern part of the continent.",
},
{
	"name": "Eldenwyld Wood",
	"parent": "Eldenwyld",
	"type": "Region",
	"supertype": "Location",
	"summary": "The largest of the three large forests that make up most of the terrain in Eldenwyld.",
},
{
	"name": "Elinunden",
	"parent": "Lott",
	"type": "Nation",
	"supertype": "Location",
	"subtype": ["Historical"],
	"summary": "The name of Eldenwyld while still ruled by the moon elves.",
},
{
	"name": "Emberscale Academy",
	"parent": "Evenstone",
	"type": "PoI",
	"subtype": ["Academy"],
	"supertype": "Location",
	"summary": "A Mihnarian Champion Academy located in Evenstone.  Run by Master Akaparthuus Emberscale, a gold dragonborn war mage.",
},
{
	"name": "Evenstone",
	"parent": "Mihnaria",
	"type": "City",
	"supertype": "Location",
	"summary": "A city in the east of Mihnaria.",
},
{
	"name": "Ever-on-Wall",
	"parent": "Eldenwyld",
	"type": "City",
	"supertype": "Location",
	"summary": "A halfling town in Eldenwyld built upon a wall of the Kingdom of the Moon, high enough out of the way that they remain largely unpurturbed by the appearances of the moon elves.",
},
{
	"name": "Faldwyl",
	"parent": "Eldenwyld",
	"type": "City",
	"supertype": "Location",
	"summary": "A city in Eldenwyld that borders all three major forests – Eldenwyld Wood, Lenwood, and Wizenwyld.",
},
{
	"name": "Farrokk",
	"parent": "Lott",
	"type": "Nation",
	"supertype": "Location",
	"summary": "A nation to the north of Dohn Durigg, inhabited largely by hill dwarfs, goliaths, and giants.",
},
{
	"name": "Felgrom",
	"parent": "Dohn Durigg",
	"type": "City",
	"supertype": "Location",
	"summary": "A city in Dohn Durigg.",
},
{
	"name": "Forrolon",
	"parent": "Eldenwyld",
	"type": "City",
	"supertype": "Location",
	"summary": "Eldenwyld town between the southwestern corner of the Lenwood and the Eldenwyld border with the Cindersands.",
},
{
	"name": "Grenmal Ridge",
	"parent": "Redwend",
	"type": "Region",
	"subtype": ["Mountain"],
	"supertype": "Location",
	"summary": "The part of the Dohn Durigg mountains within Redwend's borders.",
},
{
	"name": "Highcandle Hall",
	"parent": "Ivlin",
	"type": "PoI",
	"subtype": ["Academy"],
	"supertype": "Location",
	"summary": "A Mihnarian Champion Academy located in Ivlin.  Run by Master Dinadylia Avron, an abjurer and associate of Senate Champion Alfred Toadfeather.",
},
{
	"name": "Ivlin",
	"parent": "Mihnaria",
	"type": "City",
	"subtype": ["Capital"],
	"supertype": "Location",
	"summary": "The current capital of Mihnaria following the events of the Fall of Dragonlight Tower.",
},
{
	"name": "Lenwood",
	"parent": "Eldenwyld",
	"type": "Region",
	"supertype": "Location",
	"summary": "The smallest of the three large forests that make up most of the terrain of Eldenwyld.",
},
{
	"name": "Lowind",
	"parent": "Mihnaria",
	"type": "City",
	"supertype": "Location",
	"summary": "A town in Mihnaria along the southern edge of its border with Redwend.  Pronounced so the second syllable rhymes with \"kind,\" as the name describes the winding of a river.",
},
{
	"name": "Mad King's Tower",
	"parent": "Cindersands",
	"type": "PoI",
	"subtype": ["Tower"],
	"supertype": "Location",
	"summary": "A tower built out of envy of the Three Towers by the Mad King, now home to an expansive bazaar and trade empire.",
},
{
	"name": "Mihnaria",
	"parent": "Lott",
	"type": "Nation",
	"supertype": "Location",
	"summary": "A land at the center of the continent.  Once home to Dragonlight Tower.",
},
{
	"name": "Nindilwil",
	"parent": "Dohn Durigg",
	"type": "City",
	"supertype": "Location",
	"summary": "A largely independent gnomish metropolis located within the borders of Dohn Durigg.", // The gnomes of Nindilwil share their research with Dohn Durigg, but otherwise are not subject to its laws and is self-governing, according to an agreement reached during the Second War of Ages.  The heart of the city is the Nindilwil Collective—a technological ecosystem of constantly adapted gnomish inventions and experiments.
},
{
	"name": "Norgren",
	"parent": "Mihnaria",
	"type": "City",
	"supertype": "Location",
	"summary": "A town in Mihnaria along the northern-most part of their border with Eldenwyld.",
},
{
	"name": "Othril",
	"parent": "Redwend",
	"type": "City",
	"supertype": "Location",
	"summary": "The seat of the Tower of Ages in Redwend.",
},
{
	"name": "Panumbra",
	"parent": "Eldenwyld",
	"type": "City",
	"supertype": "Location",
	"summary": "A city on the outskirts of the moon kingdom in Eldenwyld.",
},
{
	"name": "Redwend",
	"parent": "Lott",
	"type": "Nation",
	"supertype": "Location",
	"summary": "A temperate land to the western part of the continent.  Home to the Tower of Ages and the Twilight Consortium.",
},
{
	"name": "Rylen'andil",
	"parent": "Eldenwyld",
	"type": "PoI",
	"subtype": ["River"],
	"supertype": "Location",
	"summary": "A river in the Eldenwyld and the largest tributary of Ano’andil.",
},
{
	"name": "Scadis",
	"parent": "Caithe",
	"type": "Region",
	"subtype": ["Island"],
	"supertype": "Location",
	"summary": "A Caithian island to the north of the Ignavol Rim whose citizens worship a storm giant."
},
{
	"name": "Sea of Ignavol",
	"parent": "Lott",
	"type": "Region",
	"subtype": ["Sea"],
	"supertype": "Location",
	"summary": "A large, circular sea that was once the volcano created by the primal elemental Ignavol."
},
{
	"name": "Skybreaker Academy",
	"parent": "Alerodin",
	"type": "PoI",
	"subtype": ["Academy"],
	"supertype": "Location",
	"summary": "A Mihnarian Champion Academy located in Alerodin.  Run by Master Bergi Skybreaker, who teaches the Way of the Spellbreaker.",
},
{
	"name": "Sunderfell",
	"parent": "Mihnaria",
	"type": "City",
	"supertype": "Location",
	"summary": "City in Mihnaria built around fallen Dragonlight ruins. Home of the Sunderfell Academy.",
},
{
	"name": "Sunderfell Academy",
	"parent": "Sunderfell",
	"type": "PoI",
	"subtype": ["Academy"],
	"supertype": "Location",
	"summary": "A Mihnarian Champion Academy located in Sunderfell.  Run by Master Cordelia Hawkheart, who trains in the arts of the Arcane Archer.",
},
{
	"name": "Tandriel",
	"parent": "Eldenwyld",
	"type": "City",
	"supertype": "Location",
	"summary": "A town in Eldenwyld along the northern tip of the Lenwood."
},
{
	"name": "Thunder Gold Academy",
	"parent": "Ivlin",
	"type": "PoI",
	"subtype": ["Academy"],
	"supertype": "Location",
	"summary": "A Mihnarian Champion Academy located in Ivlin.  Run by Thunder Gold, a warforged eldritch knight and veteran of the Second Dragonlight War."
},
{
	"name": "Tower of Ages",
	"parent": "Redwend",
	"type": "PoI",
	"subtype": ["Tower"],
	"supertype": "Location",
	"summary": "One of the Three Towers, located in Redwend, and the only of the three still standing.  Now ruled by the Twilight Consortium.", //  The Tower of Ages was the source of all the grand magics of the Age of Towers.  It was the first tower lost to mortals, overtaken by demons.  In an effort to reclaim the tower for mortals, they forged pacts with both celestials and devils in what has come to be known as The Twilight Consortium.  However, once the demons had been driven out of the Tower of Ages, the celestials and devils of the Twilight Consortium retained control of the tower.
},
{
	"name": "Tower of the Moon",
	"parent": "Eldenwyld",
	"type": "PoI",
	"subtype": ["Tower"],
	"supertype": "Location",
	"summary": "One of the Three Towers, located in Eldenwyld.  It vanished mysteriously during the War of the Moon with the rest of the Moon Kingdom.", //  The Tower of the Moon was once responsible for the extended longevity and good health of the people of Lott.  However, when Mihnaria went to war with Eldenwyld, the Tower of the Moon disappeared with all the citizens of Eldenwyld, now called “moon elves.”  Although many if not most of the moon elves reappear under a full moon, the Tower of the Moon has not been seen since that day.
},
{
	"name": "Underbridge",
	"parent": "Redwend",
	"type": "City",
	"supertype": "Location",
	"summary": "A halfling river town in Redwend, halfway between Arrodown and Altennott.",
},
{
	"name": "Wizenwyld",
	"parent": "Eldenwyld",
	"type": "Region",
	"supertype": "Location",
	"summary": "The second largest of the three large forests that make up most of the terrain in Eldenwyld.",
},
{
	"name": "Fall of Dragonlight Tower",
	"supertype": "Event",
	"parent": ["Dragonlight Tower", "Dragonlight War"],
	"year": 291,
	"month": 8,
	"era": "ET",
	"text": "Throughout both the War of Ages and the War of the Moon, Dragonlight Tower remained unharmed. However, after Mihnaria waged the War of the Moon against Eldenwyld, they turned their attention toward Dohn Durigg. After they failed in their military campaign against the dwarves, Dohn Durigg retaliated. In 291 ET, the dwarves sieged Dragonlight Tower, destroying it. This drew Eta Toriel to a close, and the era After the Fall began.",
},
{
	"name": "Aftermath of the fall of Dragonlight",
	"supertype": "Event",
	"parent": ["Dragonlight Tower", "Dragonlight War"],
	"year": 291,
	"month": 9,
	"era": "ET",
	"text": "When the Dragonlight Tower was destroyed, the combination of its internal, space-folding magic and the various magics Dohn Durigg used in the siege left reality around the tower distorted. Its ruins – which include the extradimensional halls spilled out into regular space – remain largely suspended in the air. Moreover, the closer anyone gets to the once-zenith of the tower, the more space and time become distorted."
},
{
	"name": "First recorded Dragonlight raider attack",
	"supertype": "Event",
	"parent": ["Dragonlight Tower", "Dragonlight War"],
	"year": 6,
	"month": 2,
	"era": "AF",
	"text": "The skyborne ruins of  Dragonlight Tower have since the fall become home to many strange things - ghosts from the battle and wild fauna both warped by the ambient magic therein. Moreover, a group of raiders have taken up hiding in the towers, learning how to survive its perils so that they can swoop down on travellers and traders from above then retreat back into the sky.  The first attack of what are now known as the Dragonlight Raiders or Dragon's Shadow came in the year 6 AF.",
},
{
	"name": "Aaric Frostlight",
	"class": "fighter",
	"faction": "Dohn Durigg Stratocracy",
	"homeland": "Dohn Durigg",
	"race": "dwarf",
"subrace": "mountain dwarf",
	"sex": "male",
	"supertype": "Character",
	"summary": "Dohn Durigg elite soldier, frozen in Dragonlight",
	"tags": ["Historical","Dragonlight Pinnacle","Dragonlight War"],
},
{
	"name": "Adelarde Elderhart",
	"title": "Lord",
	"race": "human", 
	"sex": "male",
	"class": "paladin of the ancients",
	"tags": ["HIstorical"],
	"homeland": "Eldenwyld",
	"faction": "Lost Hall",
	"supertype": "Character",
	"summary": "Founder and first Lord of the Lost Hall",
},
{
	"name": "Addrik Frostbeard",
	"race": "dwarf",
"subrace": "mountain dwarf",
	"sex": "male",
	"class": "fighter",
	"homeland": "Dohn Durigg",
	"tags":["Historical","Dragonlight Pinnacle","Dragonlight War"],
	"supertype": "Character",
	"summary": "Dohn Durigg elite soldier, frozen in Dragonlight",
},
{
	"name": "Agni Faskol", 
	"title": "Quartermaster",
	"race": "dwarf",
"subrace": "mountain dwarf",
	"sex": "male",
	"class": "npc",
	"homeland": "Dohn Durigg",
	"tier": "Renowned",
	"faction": "Dohn Durigg Stratocracy",
	"supertype": "Character",
	"summary": "Haegranhal Forge District quartermaster",
},
{
	"name": "Akaparthuus Emberscale", 
	"title": "Master",
	"race": "dragonborn",
"subrace": "gold dragonborn",
	"sex": "male",
	"class": "war mage",
	"homeland": "Mihnaria",
	"tier": "Legendary",
	"faction": "Mihnarian Champion Academies",
	"supertype": "Character",
	"summary": "Master of Emberscale Academy, friend of Alfred Toadfeather",
},
{
	"name": "Alaveris Danagris",
	"title": "Knight Commander",
	"race": "elf",
"subrace": "wood elf",
	"sex": "male",
	"class": "fighter",
	"homeland": "Eldenwyld",
	"supertype": "Character",
	"summary": "Knight Commander of the Acorn",
},
{
	"name": "Alfred Toadfeather",
	"title": "Champion",
	"race": "gnome",
"subrace": "stone gnome",
	"sex": "male",
	"class": "war mage",
	"homeland": "Mihnaria",
	"supertype": "Character",
	"summary": "champion of Liris Inhirl, friend of Akaparthuus Emberscale",
},
{
	"name": "Andalil Penthril",
	"title": "Chief",
	"race": "elf",
"subrace": "wood elf",
	"sex": "male",
	"class": "warlock of the archfey",
	"homeland": "Eldenwyld",
	"supertype": "Character",
	"summary": "Chief of Forrolon",
},
{
	"name": "Anfilt Gold",
	"title": "Forgemaster",
	"race": "warforged",
	"class":  ["fighter", "npc"],
	"homeland": "Dohn Durigg",
	"supertype": "Character",
	"summary": "Haegranhal forgemaster",
},
{
	"name": "Anfilt Seolfer",
	"race": "warforged",
	"class": "fighter",
	"tags": ["Historical"],
	"homeland": "Dohn Durigg",
	"supertype": "Character",
	"summary": "Dohn Durigg elite soldier, frozen in Dragonlight",
},
{
	"name": "Annabelle Witch-Breaker",
	"class": "Crusader",
	"race": "aasimar",
	"sex": "female",
	"class": "paladin",
	"homeland": "Redwend",
	"supertype": "Character",
	"summary": "Consortium Crusader",
},
{
	"name": "Aria Kyliel",
	"race": "elf",
"subrace": "high elf",
	"sex": "female",
	"class": "sky guard fighter",
	"homeland": "Mihnaria",
	"supertype": "Character",
	"summary": "founding member of the Sky Guard",
},
{
	"name": "Arthur Dawnhollow",
	"title": "Sentinel",
	"race": "aasimar",
	"sex": "male",
	"class": "paladin",
	"homeland": "Redwend",
	"supertype": "Character",
	"summary": "Consortium Sentinel of Light",
},
{
	"name": "Astrid Bulltoad",
	"title": "Chief",
	"race": "halfling",
"subrace": "lightfoot halfling",
	"sex": "female", 
	"homeland": "Eldenwyld",
	"supertype": "Character",
	"summary": "Chief of Ever-on-Wall",
},
{
	"name": "Barton Wandersnail",
	"race": "gnome",
"subrace": "forest gnome",
	"sex": "male",
	"class": "druid",
	"homeland": "Eldenwyld",
	"supertype": "Character",
	"summary": "Eldenwyld druid",
},
{
	"name": "Bella She-Wolf",
	"title": "Adjudicator",
	"race": "dwarf",
"subrace": "hill dwarf",
	"sex": "female",
	"class": "paladin",
	"homeland": "Redwend",
	"supertype": "Character",
	"summary": "Consortium Adjudicator",
},
{
	"name": "Bergi Skybreaker",
	"title": "Master",
	"race": "dwarf",
"subrace": "mountain dwarf",
	"sex": "female",
	"class": "spellbreaker monk",
	"homeland": "Mihnaria",
	"supertype": "Character",
	"summary": "master of Skybreaker Acadaemy",
},
{
	"name": "Berellia Thallathian",
	"title": "Senator",
	"race": "elf",
"subrace": "high elf",
	"sex": "female",
	"homeland": "Mihnaria",
	"supertype": "Character",
	"summary": "Mihnarian senator",
},
{
	"name": "Bishop Brythorne",
	"title": "Adjudicator",
	"race": "human",
	"sex": "male",
	"class": "paladin",
	"homeland": "Redwend",
	"supertype": "Character",
	"summary": "Consortium Adjudicator",
},
{
	"name": "Blood-Eye",
	"race": "goblin",
	"sex": "female",
	"class": "barbarian",
	"homeland": "Dohn Durigg",
	"supertype": "Character",
	"Summary": "A scrapper with an eye-for-eye morality",
},
{
	"name": "Boom",
	"race": "goblin",
	"sex": "male",
	"class": "rogue",
	"homeland": "Dohn Durigg",
	"supertype": "Character",
	"Summary": "Specializes in sabotage, arson, and explosives",
},
{
	"name": "Brinniel Invylia",
	"race": "elf",
"subrace": "high elf",
	"sex": "female",
	"class": "war mage",
	"homeland": "Mihnaria",
	"supertype": "Character",
	"summary": "Mihnarian elite soldier, frozen in Dragonlight Tower",
},
{
	"name": "Bruun the Outlaw",
	"race": "dwarf",
"subrace": "mountain dwarf",
	"sex": "female",
	"class": "fighter",
	"homeland": "Dohn Durigg",
	"supertype": "Character",
	"summary": "scrapper and knight for Ikitiki",
},
{
	"name": "Caerris Ozwin",
	"race": "elf",
	"subrace": "avariel",
	"sex": "male",
	"class": "war mage",
	"homeland": "Mihnaria",
	"tags": ["Historical"],
	"supertype": "Character",
	"summary": "Mihnarian elite soldier, frozen in Dragonlight Tower",
},
{
	"name": "Calyravyn Mystan",
	"title": "Queen",
	"race": "elf",
"subrace": "moon elf",
	"sex": "female",
	"homeland": "Eldenwyld",
	"tags": ["Historical"],
	"supertype": "Character",
	"summary": "Queen of the moon elves",
},
{
	"name": "Celestine Witchwood",
	"title": "Sentinel", 
	"race": "human",
	"sex": "female",
	"class": "sorcerer",
	"homeland": "Redwend",
	"supertype": "Character",
	"summary": "Consortium Sentinel of Light",
},
{
	"name": "Claire Oathsworn",
	"title": "Adjudicator",
	"race": "aasimar",
	"sex": "female",
	"class": "paladin",
	"homeland": "Redwend",
	"supertype": "Character",
	"summary": "Consortium Adjudicator",
},
{
	"name": "Colborn Spark-Spitter",
	"title": "Forgemaster",
	"race": "giant",
"subrace": "fire giant",
	"sex": "male",
	"class": "npc",
	"homeland": "Dohn Durigg",
	"supertype": "Character",
	"summary": "Haegranhal forgemaster",
},
{
	"name": "Cordelia Hawkheart",
	"title": "Master",
	"race": "human",
	"sex": "female",
	"class": "abjurer",
	"homeland": "Mihnaria",
	"supertype": "Character",
	"summary": "master of Sunderfell Academy",
},
{
	"name": "Dain Ymbeard",
	"title": "Forgemaster",
	"race": "dwarf",
"subrace": "mountain dwarf",
	"sex": "male",
	"class": "npc",
	"homeland": "Dohn Durigg",
	"supertype": "Character",
	"summary": "Haegranhal forgemaster",
},
{
	"name": "Dinadylia Avron",
	"title": "Champion",
	"race": "elf",
"subrace": "high elf",
	"sex": "female",
	"class": "eldritch knight",
	"homeland": "Mihnaria",
	"supertype": "Character",
	"summary": "master of Highcandle Hall, champion of Berellia Thallathian",
},
{
	"name": "Eira Hyde",
	"title": "Quartermaster",
	"race": "dwarf",
"subrace": "mountain dwarf",
	"sex": "female",
	"class": "npc",
	"homeland": "Dohn Durigg",
	"supertype": "Character",
	"summary": "Haegranhal King’s District quartermaster",
},
{
	"name": "Eldrid Ulstagson",
	"race": "dwarf",
"subrace": "mountain dwarf",
	"sex": "male",
	"class": "rogue",
	"homeland": "Dohn Durigg",
	"tags": ["Historical"],
	"supertype": "Character",
	"summary": "Dohn Durigg elite soldier, frozen in Dragonlight",
},
{
	"name": "Elizabeth Brightfeather",
	"race": "halfling",
"subrace": "stout halfling",
	"sex": "female",
	"class": "druid",
	"homeland": "Eldenwyld",
	"supertype": "Character",
	"summary": "Eldenwyld druid",
},
{
	"name": "Elwood Wight",
	"title": "Adjudicator",
	"race": "human",
	"sex": "male",
	"class": "cleric",
	"homeland": "Redwend",
	"supertype": "Character",
	"summary": "Consortium Adjudicator",
},
{
	"name": "Enzeril Zavarian",
	"title": "Knight Commander",
	"race": "elf",
"subrace": "high elf",
	"sex": "male",
	"class": "ranger",
	"homeland": "Eldenwyld",
	"supertype": "Character",
	"summary": "Knight Commander of the Acorn",
},
{
	"name": "Eva Red-Cloak",
	"race": "human",
	"sex": "female",
	"class": "eldritch knight",
	"homeland": "Mihnaria",
	"tags": ["Historical"],
	"supertype": "Character",
	"summary": "Mihnarian elite soldier, frozen in Dragonlight Tower",
},
{
	"name": "Everil Everiss",
	"title": "Master",
	"race": "elf",
"subrace": "high elf",
	"sex": "male",
	"class": "eldritch knight",
	"homeland": "Mihnaria",
	"supertype": "Character",
	"summary": "master of the Echoing Hall (academy), veteran of the Dragonlight Wars",
},
{
	"name": "Felghthuus Gurligaath",
	"title": "Senator",
	"race": "dragonborn",
"subrace": "silver dragonborn",
	"sex": "male",
	"homeland": "Mihnaria",
	"supertype": "Character",
	"summary": "Mihnarian senator",
},
{
	"name": "Fengtoth Gold",
	"title": "Kynesgard",
	"race": "warforged",
	"class": "fighter",
	"homeland": "Dohn Durigg",
	"supertype": "Character",
	"summary": "Dohn Durigg king’s guard",
},
{
	"name": "Fengtoth Seolfer",
	"race": "warforged",
	"class": "fighter",
	"homeland": "Dohn Durigg",
	"supertype": "Character",
	"summary": "Dohn Durigg elite soldier, frozen in Dragonlight",
},
{
	"name": "Ghirgarind",
	"race": "goblin",
	"sex": "female",
	"homeland": "Dohn Durigg",
	"supertype": "Character",
	"summary": "also \“Gear-Grinder\”",
},
{
	"name": "Gerald South-Sword",
	"title": "Captain",
	"race": "human",
	"sex": "male",
	"class": "ranger",
	"homeland": "Eldenwyld",
	"supertype": "Character",
	"summary": "Captain of the Lost Hall",
},
{
	"name": "Gildalyn Zavarian",
	"title": "High Chief",
	"race": "elf",
"subrace": "wood elf",
	"sex": "female",
	"homeland": "Eldenwyld",
	"supertype": "Character",
	"summary": "High Chief of Tandriel",
},
{
	"name": "Gore-Forged",
	"race": "warforged",
	"homeland": "Dohn Durigg",
	"supertype": "Character",
	"summary": "once a Dohn Durigg soldier, mostly destroyed, and rebuilt by goblins with minimal memories of its past",
},
{
	"name": "Grivlix",
	"race": "demon",
	"supertype": "Character",
	"summary": "demon of corruption, distortion, disease, disfigurement, mutation, passion, madness of the moment",
},
{
	"name": "Gruun the Braggart",
	"title": "Kynesgard",
	"race": "dwarf",
"subrace": "mountain dwarf",
	"sex": "male",
	"class": "fighter",
	"homeland": "Dohn Durigg",
	"supertype": "Character",
	"summary": "Dohn Durigg king’s guard, jovial about the cognomen and deserving of some bragging",
},
{
	"name": "Gudrun Elg",
	"title": "Quartermaster",
	"race": "dwarf",
"subrace": "mountain dwarf",
	"sex": "female",
	"class": "npc",
	"homeland": "Dohn Durigg",
	"supertype": "Character",
	"summary": "Haegranhal Brewery District quartermaster",
},
{
	"name": "Gudrun Grey-One",
	"race": "dwarf",
"subrace": "mountain dwarf",
	"sex": "female",
	"homeland": "Dohn Durigg",
	"supertype": "Character",
	"summary": "scrapper machinist",
},
{
	"name": "Half-Jaw",
	"race": "goblin",
	"sex": "male",
	"class": "battle master",
	"homeland": "Dohn Durigg",
	"supertype": "Character",
	"summary": "general-turned-drill-sergeant for Ikitiki",
},
{
	"name": "Hector Duskdale",
	"race": "human",
	"sex": "male",
	"homeland": "Redwend",
	"supertype": "Character",
	"summary": "Redwend hunter",
},
{
	"name": "Helga Arnhoth",
	"race": "dwarf",
"subrace": "mountain dwarf",
	"sex": "female",
	"class": "rogue",
	"homeland": "Dohn Durigg",
	"tags": ["Historical"],
	"supertype": "Character",
	"summary": "Dohn Durigg elite soldier, frozen in Dragonlight",
},
{
	"name": "Ignatius the Splendid",
	"title": "Sentinel",
	"race": "human",
	"sex": "male",
	"class": "paladin",
	"homeland": "Redwend",
	"supertype": "Character",
	"summary": "Consortium Sentinel of Shadow",
},
{
	"name": "Ikitiki",
	"race": "goblin",
	"sex": "female",
	"class": "sorcerer",
	"homeland": "Dohn Durigg",
	"supertype": "Character",
	"summary": "scrapper leader who forges through transmutation, also known as \“Ink-Drink\”",
},
{
	"name": "Illedan Elveryl",
	"race": "elf",
"subrace": "wood elf",
	"sex": "male",
	"class": "druid",
	"homeland": "Eldenwyld",
	"supertype": "Character",
	"summary": "Eldenwyld druid",
},
{
	"name": "Ingari",
	"race": "demon",
	"supertype": "Character",
	"summary": "demon of nothingness, emptiness, void",
},
{
	"name": "Inzikiu",
	"race": "celestial",
	"homeland": "Redwend",
	"faction": "Twilight Consortium",
	"supertype": "Character",
	"summary": "celestial of fate, order, law, time, inevitability; member of the Twilight Consortium",
},
{
	"name": "Iona Redcloak",
	"title": "Champion",
	"race": "human",
	"sex": "female",
	"class": ["war mage", "fighter"],
	"homeland": "Mihnaria",
	"supertype": "Character",
	"summary": "champion of Felghthuus Gurligaath, sister of Rufus Redcloak",
},
{
	"name": "Ivy Ravenfrost",
	"title": "Grand Hippogriff",
	"race": "human",
	"sex": "female",
	"class": "paladin of the ancients",
	"homeland": "Eldenwyld",
	"supertype": "Character",
	"summary": "Grand Hippogriff of the Order of the Acorn",
},
{
	"name": "Ixilac",
	"race": "demon",
	"supertype": "Character",
	"summary": "demon of the swarm",
},
{
	"name": "Ixith",
	"race": "devil", 
	"supertype": "Character",
	"summary": "devil of lust, desire; makes deals with Twilight Consortium but will not officially join",
},
{
	"name": "Kayne Dawnsworn",
	"title": "Crusader",
	"race": "aasimar",
	"sex": "male",
	"class": "warlock",
	"homeland": "Redwend",
	"supertype": "Character",
	"summary": "Consortium Crusader",
},
{
	"name": "Kilian Atwood",
	"title": "Champion",
	"race": "human",
	"sex": "male",
	"class": "arcane trickster",
	"homeland": "Mihnaria",
	"supertype": "Character",
	"summary": "master of Atwood Academy and champion of Rufus Redcloak",
},
{
	"name": "Koh",
	"race": "celestial",
	"supertype": "Character",
	"summary": "celestial of purity, cleansing; opposes the Twilight Consortium",
},
{
	"name": "Kraw Seolfer",
	"race": "warforged",
	"sex": "rogue",
	"homeland": "Dohn Durigg",
	"supertype": "Character",
	"summary": "Dohn Durigg elite soldier, frozen in Dragonlight",
},
{
	"name": "Leopold Chilldeep",
	"title": "Sentinel",
	"race": "human",
	"sex": "male",
	"class": "warlock",
	"homeland": "Redwend",
	"supertype": "Character",
	"summary": "Consortium Sentinel of Shadow",
},
{
	"name": "Levistu",
	"race": "devil",
	"homeland": "Redwend",
	"faction": "Twilight Consortium",
	"supertype": "Character",
	"summary": "devil of greed, underhanded deals, trickery, deceit, secrets; member of the Twilight Consortium",
},
{
	"name": "Lily Horn-Bearer",
	"title": "Sentinel",
	"race": "tiefling",
	"sex": "female",
	"class": "warlock",
	"homeland": "Redwend",
	"supertype": "Character",
	"summary": "Consortium Sentinel of Shadow",
},
{
	"name": "Lily Longshadow",
	"title": "Knight Captain",
	"race": "halfling",
	"sex": "female",
	"class": "ranger",
	"homeland": "Eldenwyld",
	"supertype": "Character",
	"summary": "Knight Captain of the Acorn",
},
{
	"name": "Liris Inhiril",
	"title": "Senator",
	"race": "elf",
"subrace": "high elf",
	"sex": "female",
	"class": "sorcerer",
	"homeland": "Mihnaria",
	"supertype": "Character",
	"summary": "Mihnarian senator",
},
{
	"name": "Lorikelai",
	"race": "celestial",
	"supertype": "Character",
	"summary": "celestial of wisdom, learning, struggle, ritual, history",
},
{
	"name": "Luciana the Falcon",
	"title": "Knight Commander",
	"race": "human",
	"sex": "female",
	"class": "paladin of the ancients",
	"homeland": "Eldenwyld",
	"supertype": "Character",
	"summary": "Knight Commander of the Acorn",
},
{
	"name": "Lucius Lumis",
	"title": "Marshal",
	"race": "tiefling",
	"sex": "male",
	"class": "cleric",
	"homeland": "Redwend",
	"supertype": "Character",
	"summary": "Consortium Marshal",
},
{
	"name": "Luther Dunne",
	"race": "human",
	"sex": "male",
	"class": "sorcerer",
	"homeland": "Mihnaria",
	"supertype": "Character",
	"summary": "Mihnarian elite soldier, frozen in Dragonlight Tower",
},
{
	"name": "Mist Oaken-Crook",
	"race": "dwarf",
"subrace": "mountain dwarf",
	"sex": "female",
	"class": "cleric",
	"homeland": "Dohn Durigg",
	"supertype": "Character",
	"summary": "Dohn Durigg elite soldier, frozen in Dragonlight",
},
{
	"name": "Mist Thistledown",
	"title": "Captain",
	"race": "human",
	"sex": "female",
	"class": "paladin of the ancients",
	"homeland": "Eldenwyld",
	"supertype": "Character",
	"summary": "Captain of the Lost Hall",
},
{
	"name": "Molakriu",
	"race": "demon",
	"supertype": "Character",
	"summary": "demon of decay, rot, dust, time",
},
{
	"name": "Moralyn Kalrukileth",
	"title": "Master",
	"race": "elf",
"subrace": "high elf",
	"sex": "female",
	"class": "arcane archer",
	"supertype": "Character",
	"summary": "master of Kalrukileth Hall",
},
{
	"name": "Niht-Rafen Reod",
	"title": "Quartermaster",
	"race": "warforged",
	"class": ["fighter", "npc"],
	"homeland": "Dohn Durigg",
	"supertype": "Character",
	"summary": "Haegranhal Temple District quartermaster",
},
{
	"name": "Numirithki",
	"race": "celestial",
	"supertype": "Character",
	"summary": "celestial of harvest, bounty, prosperity, nature",
},
{
	"name": "Ogrin Black-Tooth",
	"title": "Adjudicator",
	"race": "goliath",
	"sex": "male",
	"class": ["warlock", "sorcerer"],
	"homeland": "Redwend",
	"supertype": "Character",
 "summary": "Consortium Adjudicator",
},
{
	"name": "Olaf Mudwing",
	"race": "human",
	"sex": "male",
	"class": "druid",
	"homeland": "Eldenwyld",
	"supertype": "Character",
	"summary": "Eldenwyld druid",
},
{
	"name": "Ori Stonespeaker",
	"race": "dwarf",
"subrace": "mountain dwarf",
	"sex": "male",
	"class": "fighter",
	"homeland": "Dohn Durigg",
	"supertype": "Character",
	"summary": "Dohn Durigg elite soldier, frozen in Dragonlight",
},
{
	"name": "Othun",
	"race": "celestial",
	"supertype": "Character",
	"summary": "celestial of revelation, truth, light; member of the Twilight Consortium",
},
{
	"name": "Otto Chilldeep",
	"title": "Marshal",
	"race": "human",
	"sex": "male",
	"class": "fighter",
	"homeland": "Redwend",
	"supertype": "Character",
	"summary": "Consortium Marshal",
},
{
	"name": "Ovina Irontongue",
	"title": "Forgemaster",
	"race": "dwarf",
"subrace": "mountain dwarf",
	"sex": "female",
	"class": "npc",
	"homeland": "Dohn Durigg",
	"supertype": "Character",
	"summary": "Haegranhal forgemaster",
},
{
	"name": "Paerilyn Palavon",
	"title": "Captain",
	"race": "elf",
"subrace": "wood elf",
	"sex": "female",
	"class": "ranger",
	"homeland": "Eldenwyld",
	"supertype": "Character",
	"summary": "Captain of the Lost Hall",
},
{
	"name": "Paranos Dalgaron",
	"title": "Knight Captain",
	"race": "elf",
"subrace": "wood elf",
	"sex": "male",
	"class": "paladin of the ancients",
	"homeland": "Eldenwyld",
	"supertype": "Character",
	"summary": "Knight Captain of the Acorn",
},
{
	"name": "Pazunu",
	"race": "devil",
	"supertype": "Character",
	"summary": "devil of imprisonment, solitude",
},
{
	"name": "Peter Troll-Hammer",
	"title": "Knight Captain",
	"race": "human",
	"sex": "male",
	"class": "fighter",
	"homeland": "Eldenwyld",
	"supertype": "Character",
	"summary": "Knight Captain of the Acorn",
},
{
	"name": "Pipi Snow-Drift",
	"race": "dwarf",
"subrace": "hill dwarf",
	"sex": "female",
	"class": "druid",
	"homeland": "Eldenwyld",
	"supertype": "Character",
	"summary": "Eldenwyld druid",
},
{
	"name": "Rex Ignus",
	"title": "Arbiter",
	"race": "genasi",
"subrace": "fire genasi",
	"sex": "male",
	"class": "fighter",
	"homeland": "Redwend",
	"supertype": "Character",
	"summary": "Consortium Arbiter",
},
{
	"name": "Risyriel Zanos",
	"title": "Champion",
	"race": "elf",
"subrace": "high elf",
	"sex": "female",
	"class": "arcane archer",
	"homeland": "Mihnaria",
	"supertype": "Character",
	"summary": "champion of Sybil Irondel",
},
{
	"name": "Rothet Cindermoth",
	"title": "Knight Captain",
	"race": "human",
	"sex": "male",
	"class": "paladin of the ancients",
	"homeland": "Eldenwyld",
	"supertype": "Character",
	"summary": "Knight Captain of the Acorn",
},
{
	"name": "Rufus Redcloak",
	"title": "Senator",
	"race": "human",
	"sex": "male",
	"class": ["fighter", "npc"],
	"homeland": "Mihnaria",
	"supertype": "Character",
	"summary": "Mihnarian senator",
},
{
	"name": "Ruktuk",
	"race": "goblin",
	"sex": "female",
	"homeland": "Dohn Durigg",
	"supertype": "Character",
	"summary": "also \"Rusk-tusk,\" scrapper demolitionist",
},
{
	"name": "Rumbagunk",
	"race": "goblin",
	"sex": "female",
	"class": "cavalier",
	"homeland": "Dohn Duirgg",
	"supertype": "Character",
	"summary": "also \"Rumble-Clunk,\" scrapper knight who uses vehicles in place of mounts; some skill in fixing machines, but greater proficiency at breaking them",
},
{
	"name": "Rustag Blatusk",
	"title": "Quartermaster",
	"race": "dwarf",
"subrace": "mountain dwarf",
	"sex": "male",
	"class": "npc",
	"homeland": "Dohn Durigg",
	"supertype": "Character",
	"summary": "Haegranhal Residential District quartermaster",
},
{
	"name": "Rustag Brunson",
	"race": "dwarf",
"subrace": "mountain dwarf",
	"sex": "male",
	"class": "ranger",
	"homeland": "Dohn Durigg",
	"tags": ["Historical"],
	"supertype": "Character",
	"summary": "Dohn Durigg elite soldier, frozen in Dragonlight",
},
{
	"name": "Ruun Seolfer",
	"race": "warforged",
	"class": "wizard",
	"homeland": "Dohn Durigg",
	"tags": ["Historical"],
	"summary": "Dohn Durigg elite soldier, frozen in Dragonlight",
},
{
	"name": "Sigrid Gullberi",
	"title": "Sentinel",
	"race": "dwarf",
"subrace": "hill dwarf",
	"sex": "female",
	"class": "paladin",
	"homeland": "Redwend",
	"supertype": "Character",
	"summary": "Consortium Sentinel of Light",
},
{
	"name": "Sigrun Brekstan",
	"title": "Rune-Speaker",
	"race": "dwarf",
"subrace": "mountain dwarf",
	"sex": "female",
	"class": "cleric",
	"homeland": "Dohn Durigg",
	"supertype": "Character",
	"summary": "Haegranhal rune-speaker",
},
{
	"name": "Sifa",
	"race": "celestial",
	"supertype": "Character",
	"summary": "celestial of serenity, peace, rest",
},
{
	"name": "Silas Fireshine",
	"title": "Crusader",
	"race": "human",
	"sex": "male",
	"class": "paladin",
	"homeland": "Redwend",
	"supertype": "Character",
	"summary": "Consortium Crusader",
},
{
	"name": "Sirasyna Barynthiel",
	"title": "Archmage",
	"race": "elf",
"subrace": "high elf",
	"sex": "female",
	"class": "wizard",
	"homeland": "Mihnaria",
	"supertype": "Character",
	"summary": "led the elves in the Dragonlight Wars, now frozen in time at the top of the Dragonight Tower",
},
{
	"name": "Skunk",
	"race": "goblin",
	"sex": "female",
	"class": "fighter",
	"homeland": "Dohn Durigg",
	"supertype": "Character",
	"summary": "also \"Skull-Knock,\" knight for Ikitiki’s tribe",
},
{
	"name": "Skybreaker Black",
	"race": "warforged",
	"class": "spellbreaker monk",
	"homeland": "Dohn Durigg",
	"supertype": "Character",
	"summary": "formerly Huund Blaec, was instrumental along with Vilgulf Skybreaker in the Dragonlight Wars, earning the same title thereafter; afterward hunted war criminals, then, when there were no more of those, rogue mages and other magical threats",
},
{
	"name": "Sofia Simon",
	"race": "human",
	"sex": "female",
	"class": "arcane archer",
	"homeland": "Mihnaria",
	"tags": ["Historical"],
	"supertype": "Character",
	"summary": "Mihnarian elite soldier, frozen in Dragonlight Tower",
},
{
	"name": "Soomozoos",
	"race": "goblin",
	"sex": "male",
	"homeland": "Dohn Durigg",
	"supertype": "Character",
	"summary": "sometimes \"Soozomoos\" because he cannot remember if he’s supposed to read right-to-left or left-to-right, also \"Soot-Muzzle\"",
},
{
	"name": "Stanley Sparkspider",
	"race": "gnome",
"subrace": "stone gnome",
	"sex": "male",
	"class": "rogue",
	"homeland": "Dohn Durigg",
	"supertype": "Character",
	"summary": "Dohn Durigg elite soldier, frozen in Dragonlight",
},
{
	"name": "Sticklesnee",
	"race": "goblin",
	"sex": "female",
	"homeland": "Dohn Durigg",
	"supertype": "Character",
	"summary": "also \"Stickersnap\"",
},
{
	"name": "Sybil Irondel",
	"title": "Senator",
	"race": "dwarf",
"subrace": "hill dwarf",
	"sex": "female",
	"homeland": "Dohn Durigg",
	"supertype": "Character",
	"summary": "Mihnarian senator",
},
{
	"name": "Syjinks",
	"race": "goblin",
	"sex": "male",
	"homeland": "Dohn Durigg",
	"supertype": "Character",
	"summary": "also \"Singe Skin\"",
},
{
	"name": "Syldris Calenthis",
	"race": "elf",
"subrace": "high elf",
	"sex": "male",
	"class": "arcane archer",
	"homeland": "Mihnaria",
	"tags": ["Historical"],
	"supertype": "Character",
	"summary": "Mihnarian elite soldier, frozen in Dragonlight Tower",
},
{
	"name": "Sylvia Rosewood",
	"title": "Chief",
	"race": "human",
	"sex": "female",
	"homeland": "Eldenwyld",
	"supertype": "Character",
	"summary": "Chief of Boartrod",
},
{
	"name": "Syrida Adalon",
	"title": "High Druid",
	"race": "elf",
"subrace": "moon elf",
	"sex": "female",
	"class": "druid",
	"homeland": "Eldenwyld",
	"supertype": "Character",
	"summary": "High Druid of the moon elves, former advisor to the Order of the White Oak, advisor to the Order of the Acorn",
},
{
	"name": "Tarft",
	"race": "goblin",
	"sex": "male",
	"homeland": "Dohn Durigg",
	"supertype": "Character",
	"summary": "also \"Tar-Foot\"",
},
{
	"name": "Thariel Ozwin",
	"title": "Master",
	"race": "elf",
	"subrace": "avariel",
	"sex": "female",
	"class": "storm stalker ranger",
	"homeland": "Mihnaria",
	"supertype": "Character",
	"summary": "academy champion",
},
{
	"name": "Therinzekri",
	"race": "celestial",
	"supertype": "Character",
	"summary": "celestial of justice, culling, survival, necessity; member of the Twilight Consortium",
},
{
	"name": "Thruun Frostbeard",
	"title": "Warmaster",
	"race": "dwarf",
	"subrace": "mountain dwarf",
	"sex": "male",
	"class": "fighter",
	"subclass": "battle master",
	"homeland": "Dohn Durigg",
	"supertype": "Character",
	"summary": "Haegranhal warmaster, descendent of Addrik Frostbeard",
},
{
	"name": "Thryne Gullhyrn",
	"title": "King",
	"race": "dwarf",
	"subrace": "mountain dwarf",
	"sex": "male",
	"class": "fighter",
	"homeland": "Dohn Durigg",
	"summary": "king of Dohn Durigg",
},
{
	"name": "Thunder Gold",
	"title": "Master",
	"race": "warforged",
	"class": "fighter",
	"subclass": "eldritch knight",
	"homeland": "Dohn Durigg",
	"supertype": "Character",
	"summary": "master of Thunder Gold Academy, veteran of the Second Dragonlight War",
},
{
	"name": "Thuunder Seolfer",
	"race": "warforged",
	"class": "fighter",
	"homeland": "Dohn Durigg",
	"tags": ["Historical"],
	"supertype": "Character",
	"summary": "Dohn Durigg elite soldier, frozen in Dragonlight",
},
{
	"name": "Timothy Thorngate",
	"title": "Lord",
	"race": "human",
	"sex": "male",
	"class": "fighter",
	"subclass": "battle master",
	"homeland": "Eldenwyld",
	"supertype": "Character",
	"summary": "Lord of the Lost Hall",
},
{
	"name": "Ursula Sparkspider",
	"race": "gnome",
	"subrace": "stone gnome",
	"sex": "female",
	"class": "wizard",
	"homeland": "Dohn Durigg",
	"supertype": "Character",
	"summary": "Dohn Durigg elite soldier, frozen in Dragonlight",
},
{
	"name": "Uhtflokk Gold",
	"title": "Kynesgard",
	"race": "warforged",
	"class": "fighter",
	"homeland": "Dohn Durigg",
	"supertype": "Character",
	"summary": "Dohn Durigg king’s guard",
},
{
	"name": "Uhtflokk Seolfer",
	"race": "warforged",
	"class": "rogue",
	"homeland": "Dohn Durigg",
	"supertype": "Character",
	"summary": "elite soldier, frozen in Dragonlight",
},
{
	"name": "Uthgar Felfoot",
	"race": "dwarf",
	"subrace": "mountain dwarf",
	"sex": "male",
	"class": "fighter",
	"homeland": "Dohn Durigg",
	"supertype": "Character",
	"summary": "Dohn Durigg elite soldier, frozen in Dragonlight",
},
{
	"name": "Uthrin Middag",
	"title": "Forgemaster",
	"race": "dwarf",
	"subrace": "mountain dwarf",
	"sex": "male",
	"class": "npc",
	"homeland": "Dohn Durigg",
	"supertype": "Character",
	"summary": "Haegranhal forgemaster",
},
{
	"name": "Uthzandiu",
	"race": "devil",
	"supertype": "Character",
	"homeland": "Redwend",
	"summary": "devil of domination, rule, conquest, enslavement; member of the Twilight Consortium",
},
{
	"name": "Uugrix",
	"race": "demon",
	"supertype": "Character",
	"summary": "demon of madness, forgetfulness, ignorance, delusions",
},
{
	"name": "Uzazaru",
	"race": "demon",
	"supertype": "Character",
	"summary": "demon of the never-was, missed misfortunes, doom",
},
{
	"name": "Vance Duskdale",
	"race": "human",
	"sex": "male",
	"homeland": "Redwend",
	"supertype": "Character",
	"summary": "Redwend hunter",
},
{
	"name": "Vilgulf Skybreaker",
	"race": "dwarf",
	"subrace": "mountain dwarf",
	"sex": "male spellbreaker",
	"class": "monk",
	"homeland": "Dohn Durigg",
	"supertype": "Character",
	"tags": ["Historical"],
	"summary": "ancestor of Bergi Skybreaker, Dohn Durigg elite soldier who led the siege against Dragonlight Tower",
},
{
	"name": "Violet Lichfel",
	"title": "Crusader",
	"race": "tiefling",
	"sex": "female",
	"class": "cleric",
	"homeland": "Redwend",
	"supertype": "Character",
	"summary": "Consortium Crusader",
},
{
	"name": "Vix Foxhollow",
	"race": "elf",
	"subrace": "wood elf",
	"sex": "female",
	"class": "wizard",
	"homeland": "Eldenwyld",
	"tags": ["Historical"],
	"supertype": "Character",
	"summary": "Eldenwyld emissary serving as Dohn Durigg elite soldier, frozen in Dragonlight",
},
{
	"name": "Vorguul",
	"race": "devil",
	"homeland": "Redwend",
	"supertype": "Character",
	"summary": "devil of war, wrath, vengeance, destruction of enemies; member of the Twilight Consortium",
},
{
	"name": "Warren Dusk-Spark",
	"race": "human",
	"sex": "male",
	"class": "fighter",
	"subclass": "eldritch knight",
	"homeland": "Mihnaria",
	"tags": ["Historical"],
	"supertype": "Character",
	"summary": "Mihnarian elite soldier, frozen in Dragonlight Tower",
},
{
	"name": "White Widow",
	"race": "warforged",
	"class": "rogue",
	"homeland": "Dohn Durigg",
	"supertype": "Character",
	"summary": "Dohn Durigg elite, formerly Waefergang Seolfer, unaffected by the Dragonlight time lock, but remained there to protect the time lock and prevent the escape of Archmage Barynthiel",
},
{
	"name": "Wynne Winterwind",
	"race": "gnome",
"subrace": "forest gnome",
	"sex": "female",
	"class": "druid",
	"supertype": "Character",
	"summary": "Eldenwyld druid",
},];